### ISSUE TITLE
Virus (Explaination of why this program may be detected as a virus)

### ISSUE THREAD

**Issue by csevrence** [Niten001/Core-Keeper-Auto-Fish#3]
I downloaded the executable and scanning it showed no virus. But after using the program it opened active directory and changed some things. It also installed malicious software that was detected by windows defender and quarantined. I'm not sure how much damage it did to my computer but I hope this can help someone.

**Comment by Xechorizo** [comment]
Hmm maybe, though false positives are also common. If software is unverified and you can't or don't read the source code and compile it yourself, don't run it.

https://www.virustotal.com/gui/file/a674b964578547573a26ea56dd289245a8714045aa82d23010508a8457e5035b/summary

**Comment by Xechorizo** [comment]
I make no guarantees, but based on the AHK, I'd wager the odds of malware are very low.

https://raw.githubusercontent.com/Niten001/Core-Keeper-Auto-Fish/main/CoreKeeperAutoFish.ahk

**Comment by Niten001** [comment]
There is no virus, the reason windows defender quarantined the program is because of windows code signing, windows only trusts programs that are signed by a registered key. This is very expensive to do, and makes no sense in a program like this.

If you want a work around, you can install Auto Hot Key and compile the AHK file yourself, and because your computer created the file, window's defender will have no problems with it. Anybody is free to read the code and verify that there is no virus in it.

However this script is very out of date as I haven't had time to play the game in several months, so it may not even work with the current fishing mechanics. Have a good one.
